config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  resources :users

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
# User model
class User < ApplicationRecord
  attr_accessor :remember_token

  before_save { self.email = email.downcase }
  validates :name,
            presence: true,
            length: { maximum: 50 }

  VALID_EMAIL_REGEX = /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  validates :email,
            presence: true,
            length: { maximum: 100 },
            format: { with: VALID_EMAIL_REGEX },
            uniqueness: { case_sensitive: false }

  has_secure_password
  validates :password,
            presence: true,
            length: { minimum: 6 }

  # returns the hash digest of the given string.
  def self.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # returns a random token
  def self.new_token
    SecureRandom.urlsafe_base64
  end

  # remembers a user in the db for use in persistent sessions
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # returns true if the given token matches the digest
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  # forgets a user
  def forget
    update_attribute(:remember_digest, nil)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
# Manage sessions for users
class SessionsController < ApplicationController
  before_action :set_user, only: [:create]
  def new; end

  def create
    if @user && check_password
      login @user
      params[:session][:remember_me] == '1' ? remember(@user) : forget(@user)
      redirect_to @user
      flash[:success] = "Welcome back #{@user.name}"
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    logout if logged_in?
    redirect_to root_url
  end

  private

    def set_user
      @user = User.find_by(email: params[:session][:email].downcase)
    end

    def check_password
      @user.authenticate(params[:session][:password])
    end
end

app/controllers/static_pages_controller.rb
# This controller helps navigate to our static pages
# Each method/action is an actual page
class StaticPagesController < ApplicationController
  def home; end

  def about; end

  def help; end

  def contact; end
end

app/controllers/users_controller.rb
# This controller helps manage users
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login @user
      flash[:success] = "#{@user.name}, Welcome to Twirra!"
      redirect_to @user
    else
      render 'new'
    end
  end

  private

    def user_params
      params
        .require(:user)
        .permit(
          :name,
          :email,
          :password,
          :password_confirmation
        )
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Returns the full title on a per-page basis
  def page_title_generator(page_title = '')
    base_title = 'Twitter Clone'
    if page_title.empty?
      base_title
    else
      page_title + ' | ' + base_title
    end
  end
end

app/helpers/sessions_helper.rb
# all helpful methods that are relevant to the sessions controller
module SessionsHelper
  # logs in the given user
  def login(user)
    session[:user_id] = user.id
  end

  # returns the current logged-in user (if any)
  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        login user
        @current_user = user
      end
    end
  end

  # returns true if the usr is logged in, otherwise false
  def logged_in?
    !current_user.nil?
  end

  # logs out the current user
  def logout
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end

  # remembers a user in a persistent session
  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  # forgets a user in persistent session
  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  def login_as(user)
    session[:user_id] = user.id
  end
end

app/helpers/static_pages_helper.rb
# :nodoc:
module StaticPagesHelper
end

app/helpers/users_helper.rb
# All User Controller specific methods
module UsersHelper
  # Returns the Gravatar for the given user
  def gravatar_for(user, image_size: 80)
    gravatar_id = Digest::MD5.hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{image_size}"
    image_tag(gravatar_url, alt: user.name, class: 'gravatar')
  end
end

app/views/layouts/_ie_shim.html.erb
<!--[if lt IE9]>
  <script src="//cdnjs.cloudfare.com/ajax/libs/html5shiv/r29/html5.min.js"></script>
<![endif]-->

app/views/layouts/_page_footer.html.erb
<footer class="footer">
  <small>
    Copyrights &copy; 
    <%= Time.now.year %>
    <%= link_to 'Mradi Kenya', 'https://mradi.co.ke/' %>
  </small>

  <nav>
    <ul>
      <li><%= link_to 'About', about_path %></li>
      <li><%= link_to 'Contact', contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_page_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">

    <%= image_tag('t-header-logo.png', alt: 'Twirra App logo', id: 'app-logo') %>
    <%= link_to 'Twirra', root_path, id: 'app-logo-text' %>

    <nav>
    
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Home', root_path %></li>
        <li><%= link_to 'Help', help_path %></li>
        
        <% if logged_in? %>
          <li><%= link_to 'Users', '#' %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>

            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to 'Settings', '#' %></li>
              <li class="divider"></li>
              <li><%= link_to 'Log out', logout_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to 'Log in', login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_rails_default_meta.html.erb
<%= csrf_meta_tags %>

<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= page_title_generator(yield(:title)) %></title>

    <%= render 'layouts/rails_default_meta' %>
    
    <!-- Older versions of IE don't support HTML5 -->
    <%= render 'layouts/ie_shim' %>
  </head>

  <body>
    
    <%= render 'layouts/page_header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>

      <%= render 'layouts/page_footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, 'error') %>
    </div>

    <ul>
      <% @user.errors.full_messages.uniq.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, 'About') %>

<h1>About</h1>

<p>
  The <a href="https://www.railstutorial.org"><em>Ruby on Rails Tutorial</em></a>
  is a <a href="https://www.railstutorial.org/book">book</a> and a 
  <a href="http://screencasts.railstutorial.org">screencast series</a> to teach
  Web Development with <a href="rubyonrails.org">Ruby on Rails</a>.
</p>

<p>
  This is the main application built while reading that book.
  <br>
  The student's name was <a href="https://mradi.co.ke">Ng'ethe Maina</a>.
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>

<h1>Contact</h1>

<p>
  Contact the Ruby on Rails Tutorial about the Twitter clone app at the
  <a href="https://www.railstutorial.org/contact">contact page</a>.
</p>

<p>
  Contact the author of this specific Twitter clone app at his
  <a href="https://www.mradi.co.ke/contact-us/"> contact page</a>.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>

<h1>Help</h1>
<p>
  Get help on the Ruby on Rails Tutorial at the 
  <a href="https://www.railstutorial.org/help">Rails Tutorial help page.</a>
  <br> 
  <br>
  To get help on this application, see the
  <a href="https://www.railstutorial.org/book">
    <em>Ruby on Rails Tutorial</em> book
  </a>.
</p> 

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>Welcome to Twirra</h1>
  <h2>
    This was made as a project in the 
    <a href="https://www.railstutorial.org/">Ruby on Rails Tutorial </a> - sample application.
  </h2>

  <%= link_to 'Sign Up now!', signup_path, class: 'btn btn-lg btn-primary' %>

  <%#= image_tag('t-kids-using-tablet.jpg', alt: 'two babies using a tablet') %>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign Up') %>

<h1>Sign up</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user, url: signup_path) do |form| %>
      <%= render 'shared/error_messages' %>

      <div class="form-label-group">
          <%= form.text_field :name, 
            class: 'form-control', 
            placeholder: 'James Bond' %>
          <%= form.label :name, 'Your Name' %>
      </div>

      <div class="form-label-group">
        <%= form.email_field :email, 
          class: 'form-control', 
          placeholder: 'jbond@mi6.go.uk' %>
        <%= form.label :email, 'Your Email' %>      
      </div>

      <div class="form-label-group">
        <%= form.password_field :password, 
          class: 'form-control', 
          placeholder: 'A secret phrase only you know' %>
        <%= form.label :password %>
      </div>

      <div class="form-label-group">
        <%= form.password_field :password_confirmation, 
          class: 'form-control', 
          placeholder: 'Confirm This secret phrase' %>
        <%= form.label :password_confirmation, 'Confirm Password' %>
      </div>     

      <%= form.submit 'Create my account', class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
</div>


<p>
  Created: <%= @user.created_at %>
</p><p>
  Last Updated on: <%= @user.updated_at %>
</p>